name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
         pip install Cython
         pip install -r requirements.txt
         python scripts/modeling.py
      - name: write to CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" >> report.md
          cat models/metrics.txt >> report.md

          echo "## Sample Data" >> report.md
          
          echo "## Data Visualization" >> report.md
          cml publish images/fi.png --md >> report.md
          
          cml send-comment report.md